/* =====================================================================
   MAGICHELP — PEOPLE HELPED (sidebar ticker)
   Generated by admin.html. Replace the helped-data.js file in your site
   folder with this downloaded file to publish these changes.
   ===================================================================== */

window.MAGICHELP_HELPED = [
  {
    "week": "this",
    "name": "Nandhan Kumar S.",
    "phone": "+91 9441-213-0XXX"
  },
  {
    "week": "this",
    "name": "Manjunath G.",
    "phone": "+91 8142-891-7XXX"
  },
  {
    "week": "this",
    "name": "Annappan K.",
    "phone": "+91 6303-415-9XXX"
  },
  {
    "week": "this",
    "name": "Mathur Singh M.",
    "phone": "+91 9931-112-6XXX"
  },
  {
    "week": "last",
    "name": "Dayal Patil R.",
    "phone": "+91 7201-988-1XXX"
  },
  {
    "week": "last",
    "name": "Shyam Nath Tripathi",
    "phone": "+91 8541-266-4XXX"
  },
  {
    "week": "last",
    "name": "Kusum Bholekar",
    "phone": "+91 9553-247-8XXX"
  },
  {
    "week": "last",
    "name": "Yogeshwar Sahoo",
    "phone": "+91 8665-2273-0XXX"
  }
];
