/* =====================================================================
   MAGICHELP — SUCCESS STORIES
   Generated by admin.html. Replace the stories-data.js file in your site
   folder with this downloaded file to publish these changes.
   ===================================================================== */

window.MAGICHELP_STORIES = [
  {
    "date": "2026-08-08",
    "name": "Breakdown Auto Driver",
    "subtitle": "No hope, single income source",
    "image": "story-1.svg",
    "paragraphs": [
      "Dayal, an auto driver based out of Davangere met with an deadly injury. Lost the vehicle but safely cameout, struggling hard for house hold challenges requested on Magic Help more than 600 helpers helped to settle down for some time until everything recovers."
    ]
  },
  {
    "date": "2026-08-07",
    "name": "Shobana's Jaundice Suffering",
    "subtitle": "No help, 2 kids, Widow",
    "image": "story-2.svg",
    "paragraphs": [
      "Its a story of daily wager works at construction site for 650/- a day holding a 2 year toddler and 4 year girl. Lost husband with asthma. Suffering with Jaundice. Found some meaningful help by her supervisor raising 7000 a little to keep her going."
    ]
  },
  {
    "date": "2026-08-05",
    "name": "Groceries for a House of Four",
    "subtitle": "When a broken wrist met an emergency",
    "image": "story-3.svg",
    "paragraphs": [
      "A bad fall left Aisha with a wrist in a cast and three kids who still needed dinner. Carrying bags up two storeys of stairs was, for a week, simply impossible.",
      "Two MagicHelp neighbors — Dana and Tom, who didn't know each other before this — split the week between them, dropping off groceries every other day without being asked twice.",
      "By the time Aisha's cast came off, both had become regular faces on her street. \"I asked for groceries,\" she said. \"What I got was two new friends.\""
    ]
  },
  {
    "date": "2026-08-03",
    "name": "Sudden father's demise, last riots by our community",
    "subtitle": "When the house is dark, daylight mattered most",
    "image": "story-4.svg",
    "paragraphs": [
      "Father went curing water on the road work early morning, storms fall electricity lines down. Electricution made a person dissappear.",
      "\"She didn't just save the shirt,\" Leo said. \"She kept my head straight for the next two hours, and that's the part that actually got me the job.\""
    ]
  },
  {
    "date": "2026-08-01",
    "name": "A Spare Hour, Borrowed Back",
    "subtitle": "Moving day, minus the moving truck",
    "image": "story-5.svg",
    "paragraphs": [
      "Devon's moving help canceled the morning of, leaving a one-bedroom apartment and a rental truck due back by 5pm with nobody to lift the couch.",
      "Four MagicHelp members showed up within the hour — none of them knew Devon before that morning. The truck went back on time, and the couch made it up three flights without a scratch.",
      "\"I keep the group chat from that day,\" Devon said. \"It's mostly memes now. But it started because four strangers decided my Saturday mattered.\""
    ]
  },
  {
    "date": "2026-07-30",
    "name": "Homework Help, Every Wednesday",
    "subtitle": "A single dad, a tricky algebra unit, and a retired teacher",
    "image": "story-6.svg",
    "paragraphs": [
      "Sam was working two jobs and watching his daughter fall behind in algebra, with no evening hours left to help her catch up himself.",
      "Retired math teacher Wen Li saw the request and offered something bigger than a one-time fix: an hour every Wednesday, for as long as it was useful.",
      "Six weeks later, Sam's daughter brought home a B+ on her unit test. Wen Li still comes by on Wednesdays — \"mostly for the cookies now,\" she jokes."
    ]
  }
];
